name: 'ğŸ•µï¸â€â™‚ï¸ Check bundle size'
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  bundlecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: carlesnunez/check-my-bundlephobia@v1.7.0
        with:
          repo-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          ignore-dev-dependencies: true
